### ISSUE TITLE
Temporary repo context directory cannot be cleaned up on Windows

### ISSUE THREAD

**Issue by faph** [asottile/all-repos#156]
On Windows all files in `.git/` dir are marked as read-only. On Windows, that means that they cannot be deleted by the `tempfile.TemporaryDirectory` context manager ("Access is denied").

One explicit way to fix this is to do something like this on every file in `.git/` prior to exiting the temp dir context manager:

```
os.chmod(path, stat.S_IWUSR)
```

See also https://gitpython.readthedocs.io/en/stable/reference.html?highlight=rmtree#git.util.rmtree for implementation.

**Comment by asottile** [comment]
Seems to work fine for me on windows -- do you have a specific reproduction or error (your issue does not contain one)?

```
C:\Users\asott>python
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tempfile
>>> import subprocess
>>> with tempfile.TemporaryDirectory() as tmpdir:
...     subprocess.check_call(('git', 'clone', 'https://github.com/asottile/astpretty', tmpdir))
...
Cloning into 'C:\Users\asott\AppData\Local\Temp\tmp1laa2gyv'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 297 (delta 6), reused 0 (delta 0), pack-reused 281 eceiving objects:  75% (22
Receiving objects: 100% (297/297), 59.51 KiB | 1.98 MiB/s, done.
Resolving deltas: 100% (165/165), done.
0
>>>
```

**Comment by faph** [comment]
If I execute your example, I get 

```
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\x\\AppData\\Local\\Temp\\tmpho2fabiy\\.git\\objects\\pack\\pack-7bd0124ffc5964ab1db540ea14b92b2a1749b9db.idx'
```

Only differences: I'm on Python 3.6.8 and cloning using SSH.

**Comment by faph** [comment]
https://bugs.python.org/issue26660 and https://github.com/python/cpython/pull/10320: Seems this was fixed in Python 3.8?

**Comment by asottile** [comment]
3.8b1 it looks like, yes -- I recommend upgrading!

**Comment by CAM-Gerlach** [comment]
Also, it may not help right away but FWIW, things should improve further in Python 3.10 for the remaining cases of OS-level removal problems that python/cpython#10320 cannot avoid (in-use files, transient errors, I/O failures, etc). Assuming python/cpython#24793 lands, you'll be able to explicitly pass `ignore_cleanup_errors=True` (or whatever we end up calling it) to `TemporaryDirectory` as well as manually re-run `cleanup()` multiple times for best-effort deletion of all possible files, as @asottile expressed interest in on bpo-25024 .

**Comment by teddyross** [comment]
Just an FYI, in 3.9.2 the issue reappears if you do an os.chdir in the block:

```python
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tempfile
>>> import subprocess
>>> import os
>>> with tempfile.TemporaryDirectory() as tmpdir:
...     os.chdir(tmpdir)  # this causes the issue again
...     subprocess.check_call(('git', 'cloned', 'https://github.com/asottile/astpretty', tmpdir))
```
You get a bunch of these:
```python
Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\tempfile.py", line 801, in onerror
    _os.unlink(path)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\MYNAME~1\\AppData\\Local\\Temp\\tmpei9gfw4b'
```
Followed by this until max recursion depth:
```python
 File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\tempfile.py", line 804, in onerror
    cls._rmtree(path)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\tempfile.py", line 812, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\tempfile.py", line 798, in onerror
    resetperms(path)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\tempfile.py", line 790, in resetperms
    _os.chflags(path, 0)
RecursionError: maximum recursion depth exceeded while calling a Python object
>>>
```

**Comment by asottile** [comment]
does the issue persist if you use `chdir` in a contextmanager-like way? https://github.com/asottile/all-repos/blob/8f2e9bf915fb23a351238b2c32dacd1a326b3ebf/all_repos/autofix_lib.py#L122-L129
